backward compatability between erlang 16 and 17,18,19
alertlogic/jesse pull request #8
Opened 2017-02-27 11:23 UTC by zdaniel86

### Problem
Current master branch is not compiling under erlang 16 any more.
built-in `dict()` type is deprecated in erlang 17 and removed in older releases, but it produces warning in erlang 16.

### Soltution
Make the code compilable in both erlang 16 and older releases via erlang preprocessor.

2017-02-27 11:38 UTC, kkuzmin commented
+1, thanks @zdaniel86

2017-02-27 12:06 UTC, lilrooness commented on src/jesse_json_path.erl
> +                      | dict() | gb_tree:tree() | term().
this module will still not compile under erlang 16 - you have ```gb_tree:tree()``` still

2017-02-27 12:15 UTC, zdaniel86 commented on rebar.config
> +           , {platform_define, "^[0-9]+", deprecated_types}
platform_define  = OtpRelease ++ “-“ ++ SysArch ++ “-“ ++ Words.

where

OtpRelease = erlang:system_info(otp_release).
SysArch = erlang:system_info(system_architecture).
Words = integer_to_list(8 * erlang:system_info({wordsize, external})).


Erlang 16 and older starting from the letter but newer version 17,18,19 starting from the number

2017-02-28 10:45 UTC, zdaniel86 commented on src/jesse_json_path.erl
> +                      | dict() | gb_tree:tree() | term().
I don't know why but it compiles.

2017-02-28 11:20 UTC, alexturkin commented on src/jesse_json_path.erl
> +                      | dict() | gb_tree:tree() | term().
@zdaniel86  I don't understand why it compiles, but please change to  `gb_trees:tree()`: in both https://github.com/erlang/otp/blob/OTP-19.1/lib/stdlib/src/gb_trees.erl#L160  there is such module as `gb_trees`, but there is definitely no such things as `gb_tree`

2017-02-28 11:25 UTC, lilrooness commented on src/jesse_json_path.erl
> +                      | dict() | gb_tree:tree() | term().
@alexturkin What you suggested will actually make it fail in e16
```
src/jesse_json_path.erl:18: referring to built-in type dict as a remote type; please take out the module name
Compiling src/jesse_json_path.erl failed:
```

2017-03-01 11:24 UTC, alexturkin requested changes
@zdaniel86 so basically +1, but 

1) please rename `deprecated_types` to `namespaced_types`, 
2) please use `gb_trees:tree` instead to make dialyzer happy

2017-03-01 11:24 UTC, alexturkin commented on src/jesse_json_path.erl
> +                      | dict() | gb_tree:tree() | term().
@zdaniel86 to support my proposal to change to `gb_treeS`:

```
$ dialyzer --src src
  Checking whether the PLT /Users/aturkin/.dialyzer_plt is up-to-date... yes
  Proceeding with analysis...
jesse_schema_validator.erl:398: The pattern 'true' can never match the type 'ok'
jesse_schema_validator.erl:399: The pattern 'false' can never match the type 'ok'
Unknown types:
  gb_tree:tree/0
  jesse:accumulator/0
  json_schema_path:path/0
  json_schema_validator:error/0
 done in 0m1.74s
```

so dialyzer is unhappy with `gb_tree:` and happy with `gb_treeS`.

2017-03-01 14:16 UTC, alexturkin approved these changes

2017-03-01 14:16 UTC, merged